// <auto-generated />
using System;
using ComicBooksExchangeAppAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComicBooksExchangeAppAPI.Migrations
{
    [DbContext(typeof(ComicBooksExchangeDbContext))]
    partial class ComicBooksExchangeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComicBooksExchangeAppAPI.Models.Comic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Characters")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ConditionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionGrade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CurrentLoanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateListed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Era")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnLoan")
                        .HasColumnType("bit");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LoanReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Comics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Characters = "Spider-Man, Punisher, Jackal",
                            ConditionDescription = "Slight spine stress, bright colors. Classic issue.",
                            ConditionGrade = "Very Fine",
                            CoverImageUrl = "https://cdn.marvel.com/u/prod/marvel/i/mg/e/b0/57b7694649690/clean.jpg",
                            DateListed = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "First appearance of the Punisher. One of the most significant Bronze Age issues.",
                            Era = "Bronze Age",
                            Genre = "Superhero",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 129,
                            OwnerId = 1,
                            OwnerNotes = "Handle with care - this is a key issue.",
                            PublicationDate = new DateTime(1974, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Marvel",
                            Title = "The Amazing Spider-Man"
                        },
                        new
                        {
                            Id = 2,
                            Characters = "Spider-Man, Green Goblin, Gwen Stacy",
                            ConditionDescription = "Minor wear, complete story. Historic issue.",
                            ConditionGrade = "Fine",
                            CoverImageUrl = "https://cdn.marvel.com/u/prod/marvel/i/mg/a/00/57b71f662fdc8/clean.jpg",
                            DateListed = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The Night Gwen Stacy Died. The comic that changed everything about superhero storytelling.",
                            Era = "Bronze Age",
                            Genre = "Superhero",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 121,
                            OwnerId = 1,
                            OwnerNotes = "One of the most important comics ever published. Read with tissues.",
                            PublicationDate = new DateTime(1973, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Marvel",
                            Title = "The Amazing Spider-Man"
                        },
                        new
                        {
                            Id = 3,
                            Characters = "Hulk, Wolverine, Wendigo",
                            ConditionDescription = "Some spine wear, complete with MVS stamp.",
                            ConditionGrade = "Very Good",
                            CoverImageUrl = "https://cdn.marvel.com/u/prod/marvel/i/mg/9/d0/5c93f5a6e62b7/clean.jpg",
                            DateListed = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "First full appearance of Wolverine. The Bronze Age key issue.",
                            Era = "Bronze Age",
                            Genre = "Superhero",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 181,
                            OwnerId = 1,
                            OwnerNotes = "The book that launched Wolverine! MVS intact.",
                            PublicationDate = new DateTime(1974, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Marvel",
                            Title = "Incredible Hulk"
                        },
                        new
                        {
                            Id = 4,
                            Characters = "X-Men, Storm, Wolverine, Colossus, Nightcrawler",
                            ConditionDescription = "Tight binding, vibrant cover. Small corner crease.",
                            ConditionGrade = "Fine",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/81WxtKOsJrL._AC_UF894,1000_QL80_.jpg",
                            DateListed = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The relaunch that made X-Men the biggest franchise in comics. Introduces Storm, Colossus, Nightcrawler, and more.",
                            Era = "Bronze Age",
                            Genre = "Superhero",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 1,
                            OwnerId = 1,
                            OwnerNotes = "Start of the Claremont era. Essential reading.",
                            PublicationDate = new DateTime(1975, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Marvel",
                            Title = "Giant-Size X-Men"
                        },
                        new
                        {
                            Id = 5,
                            Characters = "Morpheus, Dream, Cain, Abel",
                            ConditionDescription = "Excellent condition, stored properly since purchase.",
                            ConditionGrade = "Near Mint",
                            CoverImageUrl = "https://static.dc.com/dc/files/default_images/sandman_1_5bdcac3465cb99.69674278.jpg?w=640",
                            DateListed = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Neil Gaiman's masterpiece begins. The comic that proved comics could be literature.",
                            Era = "Modern Age",
                            Genre = "Fantasy/Horror",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 1,
                            OwnerId = 2,
                            OwnerNotes = "Start of the greatest comic series ever written. Mature readers.",
                            PublicationDate = new DateTime(1989, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "DC/Vertigo",
                            Title = "Sandman"
                        },
                        new
                        {
                            Id = 6,
                            Characters = "Swamp Thing, Abby Cable",
                            ConditionDescription = "Alan Moore's first issue. Excellent condition.",
                            ConditionGrade = "Very Fine",
                            CoverImageUrl = "https://imgix-media.wbdndc.net/ingest/book/preview/38880d58-1b51-4aca-9e18-80337ef0a9f8/62d92087-bb30-4f40-bf53-cbedfbc52db9/0.jpg",
                            DateListed = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The Anatomy Lesson. Alan Moore reimagines Swamp Thing in this legendary issue that changed horror comics.",
                            Era = "Copper Age",
                            Genre = "Horror",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 21,
                            OwnerId = 2,
                            OwnerNotes = "Moore's first issue. One of the most important comics of the 80s.",
                            PublicationDate = new DateTime(1984, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "DC",
                            Title = "Saga of the Swamp Thing"
                        },
                        new
                        {
                            Id = 7,
                            Characters = "John Constantine",
                            ConditionDescription = "Good reading copy. Some minor wear.",
                            ConditionGrade = "Fine",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/716ZMMCUw7L._AC_UF1000,1000_QL80_.jpg",
                            DateListed = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "John Constantine gets his own series. Working-class horror meets social commentary.",
                            Era = "Modern Age",
                            Genre = "Horror/Urban Fantasy",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 1,
                            OwnerId = 2,
                            OwnerNotes = "Constantine at his best. Mature content throughout the series.",
                            PublicationDate = new DateTime(1988, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "DC/Vertigo",
                            Title = "Hellblazer"
                        },
                        new
                        {
                            Id = 8,
                            Characters = "Jesse Custer, Tulip O'Hare, Cassidy",
                            ConditionDescription = "Well-preserved, bright white pages.",
                            ConditionGrade = "Very Fine",
                            CoverImageUrl = "https://static.wikia.nocookie.net/marvel_dc/images/8/82/Preacher_01b.jpg",
                            DateListed = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Garth Ennis and Steve Dillon's controversial masterpiece begins. A Texas preacher gains the power of God.",
                            Era = "Modern Age",
                            Genre = "Action/Dark Comedy",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 1,
                            OwnerId = 2,
                            OwnerNotes = "WARNING: Extremely mature content. Not for the easily offended.",
                            PublicationDate = new DateTime(1995, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "DC/Vertigo",
                            Title = "Preacher"
                        },
                        new
                        {
                            Id = 9,
                            Characters = "X-Men, Thunderbird, Count Nefaria",
                            ConditionDescription = "Solid copy. Death of Thunderbird story.",
                            ConditionGrade = "Fine",
                            CoverImageUrl = "https://cdn.marvel.com/u/prod/marvel/i/mg/3/50/58a60168b290d/clean.jpg",
                            DateListed = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The new X-Men's first regular issue. Death of Thunderbird. Claremont's run truly begins.",
                            Era = "Bronze Age",
                            Genre = "Superhero",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 94,
                            OwnerId = 3,
                            OwnerNotes = "First issue of the regular series with new team.",
                            PublicationDate = new DateTime(1975, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Marvel",
                            Title = "Uncanny X-Men"
                        },
                        new
                        {
                            Id = 10,
                            Characters = "X-Men, Kitty Pryde, Emma Frost",
                            ConditionDescription = "First Kitty Pryde! Excellent condition.",
                            ConditionGrade = "Very Fine",
                            CoverImageUrl = "https://cdn.marvel.com/u/prod/marvel/i/mg/3/e0/519b7f491722f/clean.jpg",
                            DateListed = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "First appearance of Kitty Pryde and Emma Frost. The Dark Phoenix Saga begins.",
                            Era = "Bronze Age",
                            Genre = "Superhero",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 129,
                            OwnerId = 3,
                            OwnerNotes = "Essential issue. Beginning of the greatest X-Men story ever.",
                            PublicationDate = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Marvel",
                            Title = "Uncanny X-Men"
                        },
                        new
                        {
                            Id = 11,
                            Characters = "X-Men, Phoenix, Imperial Guard",
                            ConditionDescription = "Complete. Dark Phoenix finale. Some spine wear.",
                            ConditionGrade = "Fine",
                            CoverImageUrl = "https://cdn.marvel.com/u/prod/marvel/i/mg/6/80/5372a8d26e25e/clean.jpg",
                            DateListed = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The death of Phoenix. One of the most emotional issues in comics history.",
                            Era = "Bronze Age",
                            Genre = "Superhero",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 137,
                            OwnerId = 3,
                            OwnerNotes = "Bring tissues. Still gets me after all these years.",
                            PublicationDate = new DateTime(1980, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Marvel",
                            Title = "Uncanny X-Men"
                        },
                        new
                        {
                            Id = 12,
                            Characters = "X-Men, Future Wolverine, Sentinels",
                            ConditionDescription = "Days of Future Past part 1! Excellent copy.",
                            ConditionGrade = "Very Fine",
                            CoverImageUrl = "https://cdn.marvel.com/u/prod/marvel/i/mg/6/40/64e760f6051cb/clean.jpg",
                            DateListed = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Days of Future Past begins. The story that defined dystopian superhero comics.",
                            Era = "Bronze Age",
                            Genre = "Superhero",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 141,
                            OwnerId = 3,
                            OwnerNotes = "The iconic cover. Essential reading for any X-Men fan.",
                            PublicationDate = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Marvel",
                            Title = "Uncanny X-Men"
                        },
                        new
                        {
                            Id = 13,
                            Characters = "Wolverine, Mariko, Silver Samurai",
                            ConditionDescription = "First limited series! Miller/Claremont classic.",
                            ConditionGrade = "Very Fine",
                            CoverImageUrl = "https://cdn.marvel.com/u/prod/marvel/i/mg/4/00/5854497f12e1f/clean.jpg",
                            DateListed = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The Claremont/Miller limited series that defined Wolverine. 'I'm the best there is at what I do.'",
                            Era = "Bronze Age",
                            Genre = "Superhero/Action",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 1,
                            OwnerId = 3,
                            OwnerNotes = "Frank Miller on Wolverine. Doesn't get better than this.",
                            PublicationDate = new DateTime(1982, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Marvel",
                            Title = "Wolverine"
                        },
                        new
                        {
                            Id = 14,
                            Characters = "Batman, Ra's al Ghul, Talia",
                            ConditionDescription = "First Ra's al Ghul! Neal Adams art. Some wear.",
                            ConditionGrade = "Fine",
                            CoverImageUrl = "https://static.wikia.nocookie.net/marvel_dc/images/9/9c/Batman_232.jpg",
                            DateListed = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "First appearance of Ra's al Ghul. O'Neil and Adams redefine Batman as the Dark Knight.",
                            Era = "Bronze Age",
                            Genre = "Superhero/Adventure",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 232,
                            OwnerId = 4,
                            OwnerNotes = "The issue that brought Batman back to his roots.",
                            PublicationDate = new DateTime(1971, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "DC",
                            Title = "Batman"
                        },
                        new
                        {
                            Id = 15,
                            Characters = "Green Lantern, Green Arrow",
                            ConditionDescription = "Start of the legendary run. Cover wear present.",
                            ConditionGrade = "Very Good",
                            CoverImageUrl = "https://static.wikia.nocookie.net/marvel_dc/images/1/1c/Green_Lantern_Vol_2_76.jpg",
                            DateListed = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The O'Neil/Adams run begins. Comics tackle social issues for the first time. A landmark in the medium.",
                            Era = "Bronze Age",
                            Genre = "Superhero/Social Commentary",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 76,
                            OwnerId = 4,
                            OwnerNotes = "Comics grow up. This changed everything.",
                            PublicationDate = new DateTime(1970, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "DC",
                            Title = "Green Lantern/Green Arrow"
                        },
                        new
                        {
                            Id = 16,
                            Characters = "Robin, Starfire, Raven, Cyborg, Beast Boy",
                            ConditionDescription = "Wolfman/Perez magic begins! Bright, tight copy.",
                            ConditionGrade = "Very Fine",
                            CoverImageUrl = "https://static.wikia.nocookie.net/marvel_dc/images/8/8b/New_Teen_Titans_Vol_1_1.jpg",
                            DateListed = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The start of DC's biggest 80s hit. Wolfman and Perez create a new generation of heroes.",
                            Era = "Bronze Age",
                            Genre = "Superhero",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 1,
                            OwnerId = 4,
                            OwnerNotes = "DC's answer to X-Men. And it was amazing.",
                            PublicationDate = new DateTime(1980, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "DC",
                            Title = "New Teen Titans"
                        },
                        new
                        {
                            Id = 17,
                            Characters = "Teen Titans, Deathstroke",
                            ConditionDescription = "First full Deathstroke! Good condition.",
                            ConditionGrade = "Fine",
                            CoverImageUrl = "https://imgix-media.wbdndc.net/ingest/book/preview/45fd1ec5-5011-4c2e-b7a1-bc6eef3029c6/b4e9f916-980a-4701-941f-88d40d97387f/0.jpg",
                            DateListed = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "First full appearance of Deathstroke the Terminator. The greatest villain of the Titans.",
                            Era = "Bronze Age",
                            Genre = "Superhero",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 2,
                            OwnerId = 4,
                            OwnerNotes = "Deathstroke's first full appearance. Key issue.",
                            PublicationDate = new DateTime(1980, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "DC",
                            Title = "New Teen Titans"
                        },
                        new
                        {
                            Id = 18,
                            Characters = "Batman, Commissioner Gordon, Harvey Dent",
                            ConditionDescription = "First print. Stored in Mylar since purchase.",
                            ConditionGrade = "Near Mint",
                            CoverImageUrl = "https://static.wikia.nocookie.net/batman/images/7/74/The_Dark_Knight_Returns.jpg",
                            DateListed = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Frank Miller reinvents Batman. The comic that changed superhero storytelling forever.",
                            Era = "Copper Age",
                            Genre = "Superhero/Dystopia",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 1,
                            OwnerId = 4,
                            OwnerNotes = "The book that proved comics could be art.",
                            PublicationDate = new DateTime(1986, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "DC",
                            Title = "Batman: The Dark Knight Returns"
                        },
                        new
                        {
                            Id = 19,
                            Characters = "Cerebus",
                            ConditionDescription = "Early indie key. Some wear but complete.",
                            ConditionGrade = "Good",
                            CoverImageUrl = "https://recalledcomics.com/CerebusTheAardvark1.jpg",
                            DateListed = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The beginning of the 300-issue epic. Dave Sim's groundbreaking independent series.",
                            Era = "Bronze Age",
                            Genre = "Fantasy/Satire",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 1,
                            OwnerId = 5,
                            OwnerNotes = "Start of the longest-running indie comic ever. A historic piece.",
                            PublicationDate = new DateTime(1977, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Aardvark-Vanaheim",
                            Title = "Cerebus the Aardvark"
                        },
                        new
                        {
                            Id = 20,
                            Characters = "Leonardo, Donatello, Raphael, Michelangelo",
                            ConditionDescription = "Third printing. Black and white indie key.",
                            ConditionGrade = "Very Good",
                            CoverImageUrl = "https://s3.amazonaws.com/comicgeeks/comics/covers/large-2032546.jpg",
                            DateListed = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Eastman and Laird's indie sensation that became a multimedia empire. Before the toys and cartoons.",
                            Era = "Copper Age",
                            Genre = "Action/Parody",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 1,
                            OwnerId = 5,
                            OwnerNotes = "The original, darker Turtles. Nothing like the cartoon.",
                            PublicationDate = new DateTime(1984, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Mirage Studios",
                            Title = "Teenage Mutant Ninja Turtles"
                        },
                        new
                        {
                            Id = 21,
                            Characters = "Cutter, Leetah, Skywise",
                            ConditionDescription = "Original printing. Wendy Pini masterpiece.",
                            ConditionGrade = "Fine",
                            CoverImageUrl = "https://static.wikia.nocookie.net/elfquest/images/2/2c/Fantasy_quarterly.jpg",
                            DateListed = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The Pinis create one of the most beloved fantasy comics ever. Groundbreaking indie work.",
                            Era = "Bronze Age",
                            Genre = "Fantasy",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 1,
                            OwnerId = 5,
                            OwnerNotes = "Fantasy comics at their finest. A complete world.",
                            PublicationDate = new DateTime(1978, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "WaRP Graphics",
                            Title = "Elfquest"
                        },
                        new
                        {
                            Id = 22,
                            Characters = "Reuben Flagg, Raul the Cat",
                            ConditionDescription = "Howard Chaykin's masterwork. Excellent condition.",
                            ConditionGrade = "Very Fine",
                            CoverImageUrl = "https://i.ebayimg.com/images/g/vfIAAOSwzlFmZNiG/s-l1600.webp",
                            DateListed = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chaykin reinvents comic book design. A satirical near-future America that proved prescient.",
                            Era = "Copper Age",
                            Genre = "Sci-Fi/Political Satire",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 1,
                            OwnerId = 5,
                            OwnerNotes = "Revolutionary design and storytelling. Way ahead of its time.",
                            PublicationDate = new DateTime(1983, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "First Comics",
                            Title = "American Flagg!"
                        },
                        new
                        {
                            Id = 23,
                            Characters = "Maggie, Hopey, Luba",
                            ConditionDescription = "Hernandez Brothers classic. First printing.",
                            ConditionGrade = "Fine",
                            CoverImageUrl = "https://i.ebayimg.com/images/g/VwgAAOSwMQxixHNs/s-l1600.webp",
                            DateListed = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The Hernandez Brothers create the most acclaimed alternative comic series. Punk rock meets magical realism.",
                            Era = "Copper Age",
                            Genre = "Drama/Slice of Life",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 1,
                            OwnerId = 5,
                            OwnerNotes = "The definitive indie comic. Literary greatness.",
                            PublicationDate = new DateTime(1982, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Fantagraphics",
                            Title = "Love and Rockets"
                        },
                        new
                        {
                            Id = 24,
                            Characters = "Dracula, Blade",
                            ConditionDescription = "First Blade appearance! Some wear but solid.",
                            ConditionGrade = "Very Good",
                            CoverImageUrl = "https://static.wikia.nocookie.net/marveldatabase/images/2/2b/Tomb_of_Dracula_Vol_1_10.jpg",
                            DateListed = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "First appearance of Blade the Vampire Slayer. Before the movies, there was Marv Wolfman's classic.",
                            Era = "Bronze Age",
                            Genre = "Horror",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 10,
                            OwnerId = 6,
                            OwnerNotes = "Blade's first appearance. Key horror comic.",
                            PublicationDate = new DateTime(1973, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Marvel",
                            Title = "Tomb of Dracula"
                        },
                        new
                        {
                            Id = 25,
                            Characters = "Dracula, Frank Drake",
                            ConditionDescription = "Gene Colan art. Start of the greatest horror run.",
                            ConditionGrade = "Fine",
                            CoverImageUrl = "https://cdn.marvel.com/u/prod/marvel/i/mg/c/30/4bb4fd44b834c/clean.jpg",
                            DateListed = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The beginning of Marvel's longest-running horror title. Colan and Wolfman create magic.",
                            Era = "Bronze Age",
                            Genre = "Horror",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 1,
                            OwnerId = 6,
                            OwnerNotes = "70 issues of horror perfection starts here.",
                            PublicationDate = new DateTime(1972, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Marvel",
                            Title = "Tomb of Dracula"
                        },
                        new
                        {
                            Id = 26,
                            Characters = "Swamp Thing, Alec Holland",
                            ConditionDescription = "Bernie Wrightson art. Classic origin issue.",
                            ConditionGrade = "Very Good",
                            CoverImageUrl = "https://static.wikia.nocookie.net/marvel_dc/images/f/fe/Swamp_Thing_Vol_1_1.jpg",
                            DateListed = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bernie Wrightson's horrifying creation rises from the swamp. Pre-dates the Moore reinvention.",
                            Era = "Bronze Age",
                            Genre = "Horror",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 1,
                            OwnerId = 6,
                            OwnerNotes = "Wrightson's gorgeous horror art. Before Moore's genius.",
                            PublicationDate = new DateTime(1972, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "DC",
                            Title = "Swamp Thing"
                        },
                        new
                        {
                            Id = 27,
                            Characters = "Ghost Rider, Johnny Blaze",
                            ConditionDescription = "First Johnny Blaze series. Good reading copy.",
                            ConditionGrade = "Fine",
                            CoverImageUrl = "https://cdn.marvel.com/u/prod/marvel/i/mg/f/90/5caf5a9b36cd8/clean.jpg",
                            DateListed = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Johnny Blaze makes his deal with the devil. Marvel's supernatural rider begins his solo journey.",
                            Era = "Bronze Age",
                            Genre = "Horror/Superhero",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 1,
                            OwnerId = 6,
                            OwnerNotes = "70s supernatural horror at its finest.",
                            PublicationDate = new DateTime(1973, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Marvel",
                            Title = "Ghost Rider"
                        },
                        new
                        {
                            Id = 28,
                            Characters = "Werewolf by Night, Moon Knight",
                            ConditionDescription = "First Moon Knight! Key Bronze Age horror issue.",
                            ConditionGrade = "Very Good",
                            CoverImageUrl = "https://cdn.marvel.com/u/prod/marvel/i/mg/9/c0/58127df9d72ac/clean.jpg",
                            DateListed = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "First appearance of Moon Knight. The character would go on to much greater fame.",
                            Era = "Bronze Age",
                            Genre = "Horror",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 32,
                            OwnerId = 6,
                            OwnerNotes = "Moon Knight's humble beginnings in a horror comic.",
                            PublicationDate = new DateTime(1975, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Marvel",
                            Title = "Werewolf by Night"
                        },
                        new
                        {
                            Id = 29,
                            Characters = "Uncle Creepy (host)",
                            ConditionDescription = "Magazine format. Some wear but complete stories.",
                            ConditionGrade = "Good",
                            CoverImageUrl = "https://images.wolfgangsvault.com/m/large/OMS797023-MZ/creepy-vintage-magazine-jan-1-1964.webp",
                            DateListed = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Warren's answer to the banned EC Comics. Magazine-format horror with legendary artists.",
                            Era = "Silver Age",
                            Genre = "Horror Anthology",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 1,
                            OwnerId = 6,
                            OwnerNotes = "Classic horror magazine. The spirit of EC lives on.",
                            PublicationDate = new DateTime(1964, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Warren Publishing",
                            Title = "Creepy"
                        },
                        new
                        {
                            Id = 30,
                            Characters = "Various",
                            ConditionDescription = "Marvel's mature magazine. Excellent condition.",
                            ConditionGrade = "Very Fine",
                            CoverImageUrl = "https://static.wikia.nocookie.net/marveldatabase/images/3/3e/Epic_Illustrated_Vol_1_1.jpg",
                            DateListed = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Marvel's answer to Heavy Metal. Mature science fiction and fantasy from top creators.",
                            Era = "Bronze Age",
                            Genre = "Anthology/Mature",
                            IsAvailable = true,
                            IsOnLoan = false,
                            IssueNumber = 1,
                            OwnerId = 6,
                            OwnerNotes = "Marvel goes mature. Beautiful magazine-format anthology.",
                            PublicationDate = new DateTime(1980, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Marvel/Epic",
                            Title = "Epic Illustrated"
                        });
                });

            modelBuilder.Entity("ComicBooksExchangeAppAPI.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BorrowerId")
                        .HasColumnType("int");

                    b.Property<string>("BorrowerNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("BorrowerReceivedComic")
                        .HasColumnType("bit");

                    b.Property<int>("ComicId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LenderConfirmedReturn")
                        .HasColumnType("bit");

                    b.Property<int>("LenderId")
                        .HasColumnType("int");

                    b.Property<string>("LenderNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("LoanDurationDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoanEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LoanRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LoanStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutboundTrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReturnTrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BorrowerId");

                    b.HasIndex("ComicId");

                    b.HasIndex("LenderId");

                    b.HasIndex("LoanRequestId")
                        .IsUnique()
                        .HasFilter("[LoanRequestId] IS NOT NULL");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("ComicBooksExchangeAppAPI.Models.LoanRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateResponded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("RequestedComicId")
                        .HasColumnType("int");

                    b.Property<int>("RequestedLoanDurationDays")
                        .HasColumnType("int");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<string>("ResponseMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ShippingMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("WithInsurance")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RequestedComicId");

                    b.HasIndex("RequesterId");

                    b.ToTable("LoanRequests");
                });

            modelBuilder.Entity("ComicBooksExchangeAppAPI.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ComicBooksExchangeAppAPI.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("CommunicationRating")
                        .HasColumnType("bit");

                    b.Property<bool>("ConditionAsDescribed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LoanId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("ReviewedUserId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<bool>("ShippingPackagingRating")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.HasIndex("ReviewedUserId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ComicBooksExchangeAppAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollectingFocus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReadingFocus");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FavoriteCharacters")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredEras")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PreferredExchangeMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PreferredDeliveryMethod");

                    b.Property<int>("SuccessfulLoans")
                        .HasColumnType("int");

                    b.Property<string>("TradePreferences")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LendingPreferences");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageRating = 4.9m,
                            Biography = "Started reading comics in 1975. Took a break in the 90s and just getting back into it. Love sharing the classics I grew up with through this lending library.",
                            CollectingFocus = "Bronze Age Marvel & DC",
                            Email = "robert@example.com",
                            FavoriteCharacters = "Spider-Man, X-Men, Teen Titans, Swamp Thing",
                            FullName = "Robert Mitchell",
                            ImageUrl = "https://i.pravatar.cc/150?img=12",
                            IsVerified = true,
                            Location = "Cleveland, OH",
                            MemberSince = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Q29taWNCb29rc1NlZWRTYWx0MjCYN7lr3RVs0TBC7ml19bRSCkbAKg==",
                            PhoneNumber = "555-0101",
                            PreferredEras = "Bronze Age, Copper Age",
                            PreferredExchangeMethod = "Mail with Insurance",
                            SuccessfulLoans = 24,
                            TradePreferences = "Handle with care! These books mean a lot to me. Prefer lending to established members.",
                            Username = "bronze_age_bob"
                        },
                        new
                        {
                            Id = 2,
                            AverageRating = 5.0m,
                            Biography = "Former bookstore owner. Passionate about mature, literary comics. The Vertigo line changed everything for me.",
                            CollectingFocus = "Vertigo & Mature Readers",
                            Email = "diana@example.com",
                            FavoriteCharacters = "Sandman, Swamp Thing, Hellblazer, Preacher",
                            FullName = "Diana Chen",
                            ImageUrl = "https://i.pravatar.cc/150?img=47",
                            IsVerified = true,
                            Location = "Portland, OR",
                            MemberSince = new DateTime(2023, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Q29taWNCb29rc1NlZWRTYWx0MjCYN7lr3RVs0TBC7ml19bRSCkbAKg==",
                            PhoneNumber = "555-0102",
                            PreferredEras = "Copper Age, Modern Age",
                            PreferredExchangeMethod = "Mail with Insurance",
                            SuccessfulLoans = 18,
                            TradePreferences = "Love introducing new readers to quality mature comics. Please respect the condition.",
                            Username = "vertigo_veteran"
                        },
                        new
                        {
                            Id = 3,
                            AverageRating = 4.8m,
                            Biography = "Have been collecting X-Men since Claremont took over. Own nearly every issue from Giant-Size #1 through the 90s. Happy to share the classics!",
                            CollectingFocus = "Complete X-Men Runs",
                            Email = "marcus@example.com",
                            FavoriteCharacters = "X-Men, Wolverine, Storm, Nightcrawler",
                            FullName = "Marcus Williams",
                            ImageUrl = "https://i.pravatar.cc/150?img=33",
                            IsVerified = true,
                            Location = "Atlanta, GA",
                            MemberSince = new DateTime(2022, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Q29taWNCb29rc1NlZWRTYWx0MjCYN7lr3RVs0TBC7ml19bRSCkbAKg==",
                            PhoneNumber = "555-0103",
                            PreferredEras = "Bronze Age, Copper Age",
                            PreferredExchangeMethod = "Mail with Insurance",
                            SuccessfulLoans = 42,
                            TradePreferences = "Claremont era is my specialty. Will lend full story arcs when possible.",
                            Username = "xmen_completist"
                        },
                        new
                        {
                            Id = 4,
                            AverageRating = 4.9m,
                            Biography = "Grew up on O'Neil/Adams Batman and the classic Teen Titans. Still think the 70s-80s were the golden era of DC storytelling.",
                            CollectingFocus = "Classic DC Bronze Age",
                            Email = "daniel@example.com",
                            FavoriteCharacters = "Batman, Green Lantern, Green Arrow, Teen Titans",
                            FullName = "Daniel Torres",
                            ImageUrl = "https://i.pravatar.cc/150?img=15",
                            IsVerified = true,
                            Location = "Phoenix, AZ",
                            MemberSince = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Q29taWNCb29rc1NlZWRTYWx0MjCYN7lr3RVs0TBC7ml19bRSCkbAKg==",
                            PhoneNumber = "555-0104",
                            PreferredEras = "Bronze Age",
                            PreferredExchangeMethod = "Mail",
                            SuccessfulLoans = 31,
                            TradePreferences = "Big on sharing Wolfman/Perez Titans and Adams-era Batman. Careful shipping always.",
                            Username = "classic_dc_dan"
                        },
                        new
                        {
                            Id = 5,
                            AverageRating = 4.7m,
                            Biography = "Was there when the indie revolution started. Own runs of many titles that launched careers. Love sharing these overlooked gems.",
                            CollectingFocus = "Early Independent Comics",
                            Email = "sarah@example.com",
                            FavoriteCharacters = "Cerebus, TMNT, Elfquest, American Flagg",
                            FullName = "Sarah McKenzie",
                            ImageUrl = "https://i.pravatar.cc/150?img=29",
                            IsVerified = true,
                            Location = "Austin, TX",
                            MemberSince = new DateTime(2023, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Q29taWNCb29rc1NlZWRTYWx0MjCYN7lr3RVs0TBC7ml19bRSCkbAKg==",
                            PhoneNumber = "555-0105",
                            PreferredEras = "Bronze Age, Copper Age",
                            PreferredExchangeMethod = "Mail with Insurance",
                            SuccessfulLoans = 15,
                            TradePreferences = "Focus on forgotten indies that deserve more attention. Happy to recommend starting points.",
                            Username = "indie_origins"
                        },
                        new
                        {
                            Id = 6,
                            AverageRating = 4.8m,
                            Biography = "Been reading horror comics since the 70s revival. Have extensive runs of Tomb of Dracula, Swamp Thing, and more.",
                            CollectingFocus = "Horror Comics & Epic Magazine",
                            Email = "henry@example.com",
                            FavoriteCharacters = "Swamp Thing, Man-Thing, Ghost Rider, Tomb of Dracula",
                            FullName = "Henry Patterson",
                            ImageUrl = "https://i.pravatar.cc/150?img=51",
                            IsVerified = true,
                            Location = "Boston, MA",
                            MemberSince = new DateTime(2023, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Q29taWNCb29rc1NlZWRTYWx0MjCYN7lr3RVs0TBC7ml19bRSCkbAKg==",
                            PhoneNumber = "555-0106",
                            PreferredEras = "Bronze Age, Copper Age",
                            PreferredExchangeMethod = "Mail",
                            SuccessfulLoans = 22,
                            TradePreferences = "Horror fans unite! These are mature comics - please be aware of content.",
                            Username = "horror_comics_hank"
                        });
                });

            modelBuilder.Entity("ComicBooksExchangeAppAPI.Models.Comic", b =>
                {
                    b.HasOne("ComicBooksExchangeAppAPI.Models.User", "Owner")
                        .WithMany("Comics")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ComicBooksExchangeAppAPI.Models.Loan", b =>
                {
                    b.HasOne("ComicBooksExchangeAppAPI.Models.User", "Borrower")
                        .WithMany("LoansAsBorrower")
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicBooksExchangeAppAPI.Models.Comic", "Comic")
                        .WithMany()
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicBooksExchangeAppAPI.Models.User", "Lender")
                        .WithMany("LoansAsLender")
                        .HasForeignKey("LenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicBooksExchangeAppAPI.Models.LoanRequest", "LoanRequest")
                        .WithOne("Loan")
                        .HasForeignKey("ComicBooksExchangeAppAPI.Models.Loan", "LoanRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Borrower");

                    b.Navigation("Comic");

                    b.Navigation("Lender");

                    b.Navigation("LoanRequest");
                });

            modelBuilder.Entity("ComicBooksExchangeAppAPI.Models.LoanRequest", b =>
                {
                    b.HasOne("ComicBooksExchangeAppAPI.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicBooksExchangeAppAPI.Models.Comic", "RequestedComic")
                        .WithMany()
                        .HasForeignKey("RequestedComicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicBooksExchangeAppAPI.Models.User", "Requester")
                        .WithMany("LoanRequestsInitiated")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("RequestedComic");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("ComicBooksExchangeAppAPI.Models.Message", b =>
                {
                    b.HasOne("ComicBooksExchangeAppAPI.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicBooksExchangeAppAPI.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("ComicBooksExchangeAppAPI.Models.Review", b =>
                {
                    b.HasOne("ComicBooksExchangeAppAPI.Models.Loan", "Loan")
                        .WithMany("Reviews")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ComicBooksExchangeAppAPI.Models.User", "ReviewedUser")
                        .WithMany("ReviewsReceived")
                        .HasForeignKey("ReviewedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComicBooksExchangeAppAPI.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loan");

                    b.Navigation("ReviewedUser");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("ComicBooksExchangeAppAPI.Models.Loan", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ComicBooksExchangeAppAPI.Models.LoanRequest", b =>
                {
                    b.Navigation("Loan");
                });

            modelBuilder.Entity("ComicBooksExchangeAppAPI.Models.User", b =>
                {
                    b.Navigation("Comics");

                    b.Navigation("LoanRequestsInitiated");

                    b.Navigation("LoansAsBorrower");

                    b.Navigation("LoansAsLender");

                    b.Navigation("ReviewsReceived");
                });
#pragma warning restore 612, 618
        }
    }
}
